### ISSUE TITLE
LAPACK API not found

### ISSUE THREAD

**Issue by iory** [ros-planning/moveit_robots#33] opened 2015-04-24 06:02 UTC
I have trouble on compiling baxter_ikfast_right_arm_plugin
```
[baxter_ikfast_right_arm_plugin] -- catkin 0.5.90                                                                                                           
[baxter_ikfast_right_arm_plugin] -- Using these message generators: gencpp;geneus;genlisp;genpy                                                             
[baxter_ikfast_right_arm_plugin] -- Eigen found (include: /usr/include/eigen3)                                                                              
[baxter_ikfast_right_arm_plugin] -- A library with BLAS API found.                                                                                          
[baxter_ikfast_right_arm_plugin] CMake Error at /usr/share/cmake-2.8/Modules/FindLAPACK.cmake:295 (message):                                                
[baxter_ikfast_right_arm_plugin]   A required library with LAPACK API not found.  Please specify library                                                    
[baxter_ikfast_right_arm_plugin]   location.                                                                                                                
[baxter_ikfast_right_arm_plugin] Call Stack (most recent call first):                                                                                       
[baxter_ikfast_right_arm_plugin]   CMakeLists.txt:31 (find_package)                                                                                         
[baxter_ikfast_right_arm_plugin]                                                                                                                            
[baxter_ikfast_right_arm_plugin]                                                                                                                            
[baxter_ikfast_right_arm_plugin] -- Configuring incomplete, errors occurred!                                                                                
[baxter_ikfast_right_arm_plugin] make: *** [cmake_check_build_system] Error 1  
```

solutions we found are either remove `find_package(LAPACK)` from CMakeList.txt or add `set(LAPACK_lapack_WORKS TRUE)` before find_package lapack. not sure which is better.

**Comment by iory** [comment] 2015-09-09 16:48
Does anyone run into the same problem?

**Comment by rethink-imcmahon** [comment] 2015-09-09 17:02
I have not seen it before, but if your pull request fixes it, then I'd be fine with merging the change

**Comment by iory** [comment] 2015-09-09 17:11
```
diff --git a/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt b/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
index 4db49ce..09a5198 100644
--- a/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
+++ b/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
@@ -28,6 +28,7 @@ include_directories(include)
 
 set(IKFAST_LIBRARY_NAME baxter_left_arm_moveit_ikfast_plugin)
 
+set(LAPACK_lapack_WORKS TRUE)
 find_package(LAPACK REQUIRED)
 
 add_library(${IKFAST_LIBRARY_NAME} src/baxter_left_arm_ikfast_moveit_plugin.cpp)
diff --git a/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt b/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
index d08f7f8..b13e020 100644
--- a/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
+++ b/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
@@ -28,6 +28,7 @@ include_directories(include)
 
 set(IKFAST_LIBRARY_NAME baxter_right_arm_moveit_ikfast_plugin)
```
then
```
$ catkin bt
==> Expanding alias 'bt' from 'catkin bt' to 'catkin b --this'
==> Expanding alias 'b' from 'catkin b --this' to 'catkin build --this'
-----------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/iori/ros/hydro_parent/devel:/opt/ros/hydro
Workspace:                   /home/iori/ros/hydro
Source Space:       [exists] /home/iori/ros/hydro/src
Build Space:        [exists] /home/iori/ros/hydro/build
Devel Space:        [exists] /home/iori/ros/hydro/devel
Install Space:     [missing] /home/iori/ros/hydro/install
DESTDIR:                     None
-----------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
-----------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
-----------------------------------------------------------------------------


-----------------------------------------------------------------------------
WARNING: Your current environment's CMAKE_PREFIX_PATH is different from the
cached CMAKE_PREFIX_PATH used the last time this workspace was built.

If you want to use a different CMAKE_PREFIX_PATH you should call `catkin
clean --all` to remove all references to the previous CMAKE_PREFIX_PATH.

Cached CMAKE_PREFIX_PATH:
	/home/iori/ros/hydro_parent/devel:/opt/ros/hydro
Current CMAKE_PREFIX_PATH:
	/opt/ros/hydro
-----------------------------------------------------------------------------
 
Found '306' packages in 0.5 seconds. 
Starting ==> baxter_ikfast_left_arm_plugin                                      
Finished <== baxter_ikfast_left_arm_plugin [ 1.3 seconds ]                      
[build] Finished.                                                               
[build] Runtime: 2.3 seconds 
```

**Comment by iory** [comment] 2015-09-09 17:14
I would appreciate it if you could merge it.

**Comment by rethink-imcmahon** [comment] 2015-09-09 17:20
I am not the maintainer of this repo, but we can ping him to merge. Can you verify the error output when this patch is not applied? Also can you verify this patch fixes things in Indigo as well as the Hydro that you posted here?

**Comment by iory** [comment] 2015-09-09 17:28
output when this patch is not applied

```
$ catkin bt
==> Expanding alias 'bt' from 'catkin bt' to 'catkin b --this'
==> Expanding alias 'b' from 'catkin b --this' to 'catkin build --this'
-----------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/iori/ros/hydro_parent/devel:/opt/ros/hydro
Workspace:                   /home/iori/ros/hydro
Source Space:       [exists] /home/iori/ros/hydro/src
Build Space:        [exists] /home/iori/ros/hydro/build
Devel Space:        [exists] /home/iori/ros/hydro/devel
Install Space:     [missing] /home/iori/ros/hydro/install
DESTDIR:                     None
-----------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
-----------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
-----------------------------------------------------------------------------
Workspace configuration appears valid.
----------------------------------------------------------------------------- 
Found '306' packages in 0.5 seconds. 
Starting ==> baxter_ikfast_left_arm_plugin                                                     
                                                                                               
[baxter_ikfast_left_arm_plugin] ==> '/home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin/build_env.sh /usr/bin/make cmake_check_build_system' in '/home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin'
-- Using CATKIN_DEVEL_PREFIX: /home/iori/ros/hydro/devel
-- Using CMAKE_PREFIX_PATH: /home/iori/ros/hydro/devel;/home/iori/ros/hydro_parent/devel;/opt/ros/hydro
-- This workspace overlays: /home/iori/ros/hydro/devel;/home/iori/ros/hydro_parent/devel;/opt/ros/hydro
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Python version: 2.7
-- Using Debian Python package layout
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- catkin 0.5.90
-- Using these message generators: gencpp;geneus;genlisp;genpy
-- Eigen found (include: /usr/include/eigen3)
-- A library with BLAS API found.
CMake Error at /usr/share/cmake-2.8/Modules/FindLAPACK.cmake:295 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
make: *** [cmake_check_build_system]  1
[baxter_ikfast_left_arm_plugin] <== '/home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin/build_env.sh /usr/bin/make cmake_check_build_system' failed with return code '2'
                                                                                                
[build] There were errors:                                                                     

    Failed to build package 'baxter_ikfast_left_arm_plugin' because the following command:

        # Command run in directory: /home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin
        /home/iori/ros/hydro/build/baxter_ikfast_left_arm_plugin/build_env.sh /usr/bin/make cmake_check_build_system

    Exited with return code: 2 
[build] Runtime: 2.0 seconds 
```

**Comment by rethink-imcmahon** [comment] 2015-09-09 20:11
@iory thanks for this trace. If you could show a functional Indigo catkin build, I'd be convinced enough to push for a merge.

**Comment by sachinchitta** [comment] 2015-09-09 20:50
@rethink-imcmahon - you have merge access.

**Comment by gavanderhoorn** [comment] 2015-09-10 06:49
Looking at versions of `FindLAPACK.cmake` that use the variable mentioned in the OP (such as [this one](https://github.com/athlonshi/Sundials-MAGMA/blob/c0236173bc338224137122e4d76736352b6c71eb/config/FindLAPACK.cmake), as the [official one](https://github.com/Kitware/CMake/blob/7eacbaed4db3c3fe5d6c0e3a31e239530a7468f1/Modules/FindLAPACK.cmake) from Kitware seems to have been changed significantly), it would seem that `LAPACK_lapack_WORKS` is a variable internal to `FindLAPACK`, which it uses to determine whether it has actually found a working LAPACK library.

I'd say that forcing it to `TRUE` - as done in #34 - from the outside is not really a fix, but more a way to force `FindLAPACK` to report that it has found a compatible LAPACK implementation. For a real fix we'd probably need to figure out why `FindLAPACK` isn't happy with any LAPACK library the OP has on his system, resulting in the reported CMake configuration error.

**Comment by gavanderhoorn** [comment] 2015-09-10 06:52
@iory: can you provide some detail on the system you are running this on? OS, ROS version, from source / debians, which LAPACK library you have installed, CMake version, specific version of `FindLAPACK.cmake`, etc.

Did this stop working 'suddenly', or has this never worked? That sort of thing.

**Comment by rethink-imcmahon** [comment] 2015-09-10 13:55
Thanks for taking a look @gavanderhoorn. My CMake-foo is not incredible, so I appreciate you weighing in here

**Comment by davetcoleman** [comment] 2016-07-31 19:04
Is this still an issue? I recently added a missing lapack dependency to the baxter config that probably addresses this.

https://github.com/ros-planning/moveit_robots/commit/5ec08593d646021a6dfb2d7c52ea6d419f485a8b

**Comment by IanTheEngineer** [comment] 2016-08-01 14:42
I was never able to reproduce this issue with my setup, but it would make sense that your build-depend addition would fix it. +1 for closing.

**Comment by v4hn** [comment] 2016-08-01 15:32
To me, this looks like a broken setup, that might have been due to the missing dep.
Closing.

**Closed by v4hn** 2016-08-01 15:32 UTC

**Comment by guanshaoheng** [comment] 2020-07-30 11:32
> ```
> diff --git a/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt b/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
> index 4db49ce..09a5198 100644
> --- a/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
> +++ b/baxter/baxter_ikfast_left_arm_plugin/CMakeLists.txt
> @@ -28,6 +28,7 @@ include_directories(include)
> 
>  set(IKFAST_LIBRARY_NAME baxter_left_arm_moveit_ikfast_plugin)
> 
> +set(LAPACK_lapack_WORKS TRUE)
>  find_package(LAPACK REQUIRED)
> 
>  add_library(${IKFAST_LIBRARY_NAME} src/baxter_left_arm_ikfast_moveit_plugin.cpp)
> diff --git a/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt b/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
> index d08f7f8..b13e020 100644
> --- a/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
> +++ b/baxter/baxter_ikfast_right_arm_plugin/CMakeLists.txt
> @@ -28,6 +28,7 @@ include_directories(include)
> 
>  set(IKFAST_LIBRARY_NAME baxter_right_arm_moveit_ikfast_plugin)
> ```
> 
> then
> 
> ```
> $ catkin bt
> ==> Expanding alias 'bt' from 'catkin bt' to 'catkin b --this'
> ==> Expanding alias 'b' from 'catkin b --this' to 'catkin build --this'
> -----------------------------------------------------------------------------
> Profile:                     default
> Extending:          [cached] /home/iori/ros/hydro_parent/devel:/opt/ros/hydro
> Workspace:                   /home/iori/ros/hydro
> Source Space:       [exists] /home/iori/ros/hydro/src
> Build Space:        [exists] /home/iori/ros/hydro/build
> Devel Space:        [exists] /home/iori/ros/hydro/devel
> Install Space:     [missing] /home/iori/ros/hydro/install
> DESTDIR:                     None
> -----------------------------------------------------------------------------
> Isolate Develspaces:         False
> Install Packages:            False
> Isolate Installs:            False
> -----------------------------------------------------------------------------
> Additional CMake Args:       None
> Additional Make Args:        None
> Additional catkin Make Args: None
> -----------------------------------------------------------------------------
> 
> 
> -----------------------------------------------------------------------------
> WARNING: Your current environment's CMAKE_PREFIX_PATH is different from the
> cached CMAKE_PREFIX_PATH used the last time this workspace was built.
> 
> If you want to use a different CMAKE_PREFIX_PATH you should call `catkin
> clean --all` to remove all references to the previous CMAKE_PREFIX_PATH.
> 
> Cached CMAKE_PREFIX_PATH:
>     /home/iori/ros/hydro_parent/devel:/opt/ros/hydro
> Current CMAKE_PREFIX_PATH:
>     /opt/ros/hydro
> -----------------------------------------------------------------------------
> 
> Found '306' packages in 0.5 seconds. 
> Starting ==> baxter_ikfast_left_arm_plugin                                      
> Finished <== baxter_ikfast_left_arm_plugin [ 1.3 seconds ]                      
> [build] Finished.                                                               
> [build] Runtime: 2.3 seconds 
> ```

this helped me work out this problem
